<a href="https://colab.research.google.com/github/kauazin05/CIAO_KKG_2026/blob/main/AULA_07/lab04_aula07_ciao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
# ==========================================================
# LAB 04 - ACO: Feromonio, Evaporacao e Atratividade
# Tema: Otimizacao de Caminhos e Grafos de Rede
# ==========================================================
import numpy as np

# Grafo de Latencia entre Roteadores (Matriz de Custo)
latency_matrix = np.array([
    [0, 5, 2, 9],
    [5, 0, 3, 1],
    [2, 3, 0, 7],
    [9, 1, 7, 0]
])

num_nodes = len(latency_matrix)
pheromone = np.ones((num_nodes, num_nodes))
rho = 0.25   # Taxa de Evaporacao


def update_pheromone(pheromone_matrix, paths, costs, rho):
    # TODO 1 RESOLVIDO: evaporacao em toda a matriz
    pheromone_matrix = (1 - rho) * pheromone_matrix

    # TODO 2 RESOLVIDO: deposito inversamente proporcional ao custo
    for path, cost in zip(paths, costs):
        for i in range(len(path) - 1):
            u, v = path[i], path[i + 1]
            pheromone_matrix[u][v] += 1.0 / cost
            pheromone_matrix[v][u] += 1.0 / cost   # grafo nao-direcionado

    return pheromone_matrix


# Simulacao mock para teste da funcao desenvolvida
mock_paths = [[0, 2, 1, 3], [0, 1, 3]]
mock_costs = [6.0, 6.0]

pheromone_inicial = np.copy(pheromone)
updated_pheromone = update_pheromone(pheromone, mock_paths, mock_costs, rho)
print("[LAB 04 - SUCESSO] Matriz de Feromonio Atualizada:\n", np.round(updated_pheromone, 4))

# Atratividade heuristica: eta = 1 / latencia (inversamente proporcional)
eta = np.where(latency_matrix > 0, 1.0 / np.where(latency_matrix == 0, 1, latency_matrix), 0.0)
print("\n[LAB 04] Matriz de Atratividade (eta = 1/latencia):\n", np.round(eta, 4))

# ==========================================================
# Simulacao de 20 rodadas para observar o efeito da evaporacao
# ==========================================================
p_sim = np.ones((num_nodes, num_nodes))
hist_13, hist_02, hist_03 = [], [], []   # arestas usadas 2x, 1x e 0x

for it in range(20):
    p_sim = update_pheromone(p_sim, mock_paths, mock_costs, rho)
    hist_13.append(p_sim[1][3])   # usada pelas 2 formigas (latencia 1)
    hist_02.append(p_sim[0][2])   # usada por 1 formiga
    hist_03.append(p_sim[0][3])   # nunca usada (latencia 9)

print(f"\n[LAB 04] Apos 20 rodadas -> aresta 1-3: {hist_13[-1]:.4f} | "
      f"aresta 0-2: {hist_02[-1]:.4f} | aresta 0-3 (nao usada): {hist_03[-1]:.4f}")

# ==========================================================
# Evolucao do feromonio em formato de tabela (saida textual)
# ==========================================================
print("\n[LAB 04] Evolucao do feromonio ao longo das rodadas:")
print(" Rodada | Aresta 1-3 (2 formigas) | Aresta 0-2 (1 formiga) | Aresta 0-3 (nao usada)")
print("--------+-------------------------+------------------------+-----------------------")
for it in range(20):
    if it < 5 or it >= 17 or (it + 1) % 5 == 0:
        print(f" {it+1:6d} | {hist_13[it]:23.4f} | {hist_02[it]:22.4f} | {hist_03[it]:21.4f}")

[LAB 04 - SUCESSO] Matriz de Feromonio Atualizada:
 [[0.75   0.9167 0.9167 0.75  ]
 [0.9167 0.75   0.9167 1.0833]
 [0.9167 0.9167 0.75   0.75  ]
 [0.75   1.0833 0.75   0.75  ]]

[LAB 04] Matriz de Atratividade (eta = 1/latencia):
 [[0.     0.2    0.5    0.1111]
 [0.2    0.     0.3333 1.    ]
 [0.5    0.3333 0.     0.1429]
 [0.1111 1.     0.1429 0.    ]]

[LAB 04] Apos 20 rodadas -> aresta 1-3: 1.3323 | aresta 0-2: 0.6677 | aresta 0-3 (nao usada): 0.0032

[LAB 04] Evolucao do feromonio ao longo das rodadas:
 Rodada | Aresta 1-3 (2 formigas) | Aresta 0-2 (1 formiga) | Aresta 0-3 (nao usada)
--------+-------------------------+------------------------+-----------------------
      1 |                  1.0833 |                 0.9167 |                0.7500
      2 |                  1.1458 |                 0.8542 |                0.5625
      3 |                  1.1927 |                 0.8073 |                0.4219
      4 |                  1.2279 |                 0.7721 |           